#!/usr/bin/env python3

import os
import sys
import shutil
import errno
import socket
import time
import argparse
import logging

import serial

class EvbPusherService:
    def __init__(self, socket_path, us_path, logger):
        self.socket_path = socket_path
        self.us_path = us_path
        self.logger = logger

    def start(self):
        self.logger.critical("Open EVB pusher serial port.")
        self.ser = serial.Serial(self.us_path, baudrate=115200, timeout=0.86, exclusive=True)
        self.logger.critical("Wait EVB pusher bootup for 3sec.")
        time.sleep(3)
        
        self.logger.critical("<<<<<<< Read out initial message from EvbPusher")
        ini_recv = self.ser.readlines(4096)
        for line in ini_recv:
            self.logger.critical("==> " + line.decode().rstrip())
        self.logger.critical("Finish read out >>>>>>>")
        
        self.logger.info("Setup/bind UNIX domain socket.")
        s = self.socket = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        s.bind(self.socket_path)
        shutil.chown(self.socket_path, group="dialout")
        os.chmod(self.socket_path, 0o770)
        self.logger.critical("Setup done. Entering listen().")
        s.listen(1)
        try:
            while True:
                connection, address = s.accept()
                self.logger.debug("connected")
                self.accepted(connection, address)
                self.logger.debug("disconnect")
        finally:
            os.remove(self.socket_path)
            self.ser.close()
            
    def accepted(self, connection, address):
        """echo the recieved data
        """
        cmd = connection.recv(256)
        self.logger.info("receive from client: {}".format(cmd.decode()))
        self.ser.write(cmd)
        self.ser.write(b'\n')
        recv = self.ser.read(4096)
        self.logger.info(recv)
        connection.send(recv)


if __name__ == '__main__':
	logging.basicConfig()
	logger = logging.getLogger(__name__)
	parser = argparse.ArgumentParser()
	parser.add_argument("-d", "--device", help="Optional: For change USB serial device path.", default="/dev/ttyEvbPusher")
	parser.add_argument("-s", "--sock", help="Optional: For change socket path.", default="/tmp/evbpusher.sock")
	parser.add_argument("--loglevel_debug",    action="store_true", help="Optional: For change loglevel to DEBUG.")
	parser.add_argument("--loglevel_info",     action="store_true", help="Optional: For change loglevel to INFO.")
	parser.add_argument("--loglevel_warning",  action="store_true", help="Optional: For change loglevel to WARNING (default).")
	parser.add_argument("--loglevel_error",    action="store_true", help="Optional: For change loglevel to ERROR.")
	parser.add_argument("--loglevel_critical", action="store_true", help="Optional: For change loglevel to CRITICAL.")
	args = parser.parse_args()
	print(args)
	if args.loglevel_critical:
		logger.setLevel(logging.CRITICAL)
	elif args.loglevel_error:
		logger.setLevel(logging.ERROR)
	elif args.loglevel_warning:
		logger.setLevel(logging.WARNING)
	elif args.loglevel_info:
		logger.setLevel(logging.INFO)
	elif args.loglevel_debug:
		logger.setLevel(logging.DEBUG)
	else:
		logger.setLevel(logging.WARNING)
	
	logger.critical("Test: loglevel CRITICAL")
	logger.error(   "Test: loglevel ERROR")
	logger.warning( "Test: loglevel WARNING")
	logger.info(    "Test: loglevel INFO")
	logger.debug(   "Test: loglevel DEBUG")
	
	if not os.path.exists(args.device):
		logger.critical("USB-Serial device({}) is not available. Abort.".format(args.device))
		sys.exit(errno.ENODEV)
	if os.path.exists(args.sock):
		logger.critical("UNIX domain socket({}) is already available. Abort.".format(args.sock))
		sys.exit(errno.EEXIST)
	server = EvbPusherService(args.sock, args.device, logger)
	server.start()
